name: Android Live TV CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUT: ${{ github.workspace }}/out
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 29
          build-tools: 29.0.2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign

      - name: Set up Gradle 5.4.1
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 5.4.1

      - name: Build LiveTv APK
        run: |
          gradle assembleRelease

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find build/outputs/apk/release/ -name '*.apk' | grep -v unsigned | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Download keystore from secrets
        run: |
          echo "$KEYSTORE_B64" | base64 -d > release.keystore
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

      - name: Zipalign APK
        run: |
          zipalign -v -p 4 "${{ steps.find_apk.outputs.apk_path }}" LiveTv-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign --ks release.keystore --ks-key-alias "$KEYSTORE_ALIAS" --ks-pass pass:"$KEYSTORE_PASSWORD" --key-pass pass:"$KEYSTORE_PASSWORD" --out LiveTv-release.apk LiveTv-aligned.apk
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: LiveTv-release-apk
          path: LiveTv-release.apk
